name: Buf CI
on:
  push:
    paths:
      - "service/proto/**"
      - "service/buf.yaml"
      - ".github/workflows/buf.yaml"
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - "service/proto/**"
      - "service/buf.yaml"
      - ".github/workflows/buf.yaml"

permissions:
  contents: read
  pull-requests: write
  
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          input: service