name: Build client binaries
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-client.yaml"
      - "client/**"
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - ".github/workflows/build-client.yaml"
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: Build binaries and test linux-amd64
        run: |
          set -ex
          
          # Build the binaries
          cd client
          make build-all
          
          # Assert that all the expected binaries were built
          [ ! -f "bin/aks-stls-bootstrap-client-amd64" ] && echo "expected aks-stls-bootstrap-client-amd64 to have been built" && exit 1
          [ ! -f "bin/aks-stls-bootstrap-client-arm64" ] && echo "expected aks-stls-bootstrap-client-arm64 to have been built" && exit 1
          [ ! -f "bin/aks-stls-bootstrap-client-amd64.exe" ] && echo "expected aks-stls-bootstrap-client-amd64.exe to have been built" && exit 1
          [ ! -f "bin/aks-stls-bootstrap-client-arm64.exe" ] && echo "expected aks-stls-bootstrap-client-arm64.exe to have been built" && exit 1

          # Make sure we can actually invoke linux/amd64
          pushd bin
            chmod +x ./aks-stls-bootstrap-client-amd64
            ./aks-stls-bootstrap-client-amd64 -h
            if [ $? -ne 0 ]; then
              echo "unable to invoke linux/amd64 binary"
              exit 1
            fi
          popd
          