name: Build client binaries
on:
  push:
    paths:
      - ".github/workflows/build-client.yaml"
      - "client/**"
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - ".github/workflows/build-client.yaml"
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: Build binaries and test linux-amd64
        run: |
          set -ex
          # Build the binaries
          cd client
          make build-all

          # Make sure we can actually invoke linux/amd64
          pushd bin
            chmod +x ./aks-stls-bootstrap-client-amd64
            ./tls-bootstrap-client-amd64 -h
            if [ $? -ne 0 ]; then
              echo "unable to invoke linux/amd64 binary"
              exit 1
            fi
          popd
          