name: "Test coverage"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests with coverage
        run: make test-coverage
      - name: Remove mocks.go lines from coverage_raw.out
        run: |
          sed '/mocks.go/d' coverage_raw.out > coverage.out
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: coverage.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
          