name: golangci-lint
on:
  push:
    branches: ["main"]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      - uses: actions/checkout@v3
      - name: golangci-lint-client
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: client
          args: --timeout=10m