name: golangci-lint-pr
on:
  push:
    paths:
      - ".github/workflows/golangci-lint-pr.yaml"
      - "client/**"
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - ".github/workflows/golangci-lint-pr.yaml"
      - "client/**"
      
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: client
          args: --timeout=5m
          only-new-issues: true