name: golangci-lint-pr
on:
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: golangci-lint-client
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: client
          only-new-issues: true
          args: --timeout=10m
      - name: golangci-lint-service
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: service
          only-new-issues: true
          args: --timeout=10m