name: Service Buf CI
on:
  pull_request:
    paths:
      - service/**

permissions:
  contents: read
  pull-requests: write
  
jobs:
  service-buf-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          input: service