name: Service Buf CI
on:
  pull_request:
    paths:
      - service/**

permissions:
  contents: read
  pull-requests: write
  
jobs:
  service-buf-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: bufbuild/buf-action@85aebf73123b5c15fd5528aaecbf9129cddf7fa7 # v1.6.0
        with:
          input: service